### ISSUE TITLE
Using Hugo module (Go Module) stored in private repo

### ISSUE THREAD

**Issue by divyakumarjain** [klakegg/docker-hugo#33] opened 2020-09-10 22:12 UTC
Need to have a way to use private Hugo module (go module). One of the way suggested in below forum is using "insteadOf" in git config url. This allows adding access token in the module Git URL when Hugo is trying to download.

https://discourse.gohugo.io/t/proper-way-to-get-private-repos-hugo-modules/21920/10

One option is to have a new ONBUILD ARG which takes a command which gets executed before "ONBUILD RUN hugo ${HUGO_CMD}".

Thoughts?

**Comment by klakegg** [comment] 2020-09-11 16:06
Duplicate of #32.

**Closed by klakegg** 2020-09-11 16:06 UTC
